# Generated by Django 6.1.1 on 2026-09-26 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangarin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='task_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangarin.task'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangarin.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangarin.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangarin.priority'),
        ),
    ]
